[package]
name = "password_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
copypasta = "0.10.2"
crossterm = "0.29.0"
passwords = "3.1.16"
rand = "0.9.2"
